import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import LocalFonts from "next/font/local";

const IbmPlexMono = LocalFonts({
  src: [
    {path: "/fonts/IBMPlexSans-Italic-VariableFont_wdth,wght.ttf", weight: "400", style: "normal"},
    {path: "/fonts/IBMPlexSans-VariableFont_wdth,wght.ttf", weight: "500", style: "normal"},
  ]
});

const BebasNeue = LocalFonts({
  src: [{path: "/fonts/BebasNeue-Regular.ttf", weight: "400", style: "normal"}],
  variable: "--font-bebas-neue",
  })

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Taz Library App",
  description: "Generated by Tazim",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${IbmPlexMono.className} ${BebasNeue.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
